title: "Other Name's Portfolio"
languageCode: en
baseURL: "https://example.me"

Params:
  name: "Mylong Name"
  role: "Software Engineer"
  email: "email2@myemail.me"
  desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta debitis reiciendis quas ex in enim nihil, a harum excepturi maiores placeat, deserunt voluptatem perspiciatis inventore. At eius assumenda temporibus perferendis."

  projects:
    - name: "Casterr"
      url: https://casterr.sbond.co
      desc: "a recorder"
      points:
        - "first big project"
      tech:
        - TypeScript
        - Vue
        - Node

    - name: "LabMaker"
      desc: "a clean and seamless"
      points:
        - "first big project"

  experience:
    - time: Jan 2020 - Present
      role: "Electron Developer"
      company: "random company"
      points:
        - "random point"
        - "random point"
        - "random point"
        - "random point"

    - time: Jun 2019 - Dec 2019
      role: "Software Engineer"
      company: "random company"
      desc: "A job where i did things and made cool things n stuff"
      points:
        - "random point"
        - "random point"
        - "random point"
        - "random point"

publishDir: ./../public
enableRobotsTXT: true

minify:
  minifyOutput: true
